### PR TITLE
HDDS-8828. Adapt TestBlockTokens to build with Hadoop 3.3

### PR DESCRIPTION
**Pull request by duongkame**
## What changes were proposed in this pull request?

TestBlockTokens uses methods that are removed in Hadoop 3.3. This prevents ozone to build with later versions of Hadoop. 

```
INFO    : [ERROR] /grid/0/jenkins/workspace/workspaceSOURCES/ozone/hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestBlockTokens.java:[243,14] cannot find symbol
INFO    :   symbol:   method setID(byte[])
INFO    :   location: variable token of type org.apache.hadoop.security.token.Token<org.apache.hadoop.hdds.security.token.OzoneBlockTokenIdentifier>
INFO    : [ERROR] /grid/0/jenkins/workspace/workspace/SOURCES/ozone/hadoop-ozone/integration-test/src/test/java/org/apache/hadoop/ozone/TestBlockTokens.java:[262,14] cannot find symbol
INFO    :   symbol:   method setPassword(byte[])
INFO    :   location: variable token of type org.apache.hadoop.security.token.Token<org.apache.hadoop.hdds.security.token.OzoneBlockTokenIdentifier>
```
 
## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-8828

## How was this patch tested?

Standard CI.

### CODE REVIEW

**Review by swamirishi — APPROVED** [review]
LGTM

**Review by swagle — APPROVED** [review]
LGTM

**Comment by duongkame** [comment]
Thanks @swamirishi @swagle for the review.

**Comment by adoroszlai** [comment]
@duongkame Ozone is built with Hadoop 3.3.5:

https://github.com/apache/ozone/blob/8ac62eb954099bb41cc90cdf9db2a664f23b739f/pom.xml#L66

`Token.setID` and `setPassword` were added by [HDFS-14611](https://issues.apache.org/jira/browse/HDFS-14611) in 3.3.0.

Did you mean build with Hadoop older than 3.3?
